FROM python:3.8.17-slim-bullseye

WORKDIR /src

COPY python/iris_classification.py .
COPY python/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


CMD ["python","iris_classification.py"]
